### ISSUE TITLE
types-versions-wildcards with exports in subdirectories

### ISSUE THREAD

**Issue by michaldudak** [andrewbranch/example-subpath-exports-ts-compat#12]
I'm trying to bring proper ESM+CJS to Material UI, Base UI, and related projects. I'm using the `types-versions-wildcards` strategy to make sure the libraries work correctly under `node10` module resolution. However, I ran into an issue, and I'm wondering if this is a TypeScript limitation or if there is a workaround.

Our source code layout looks slightly different than the example in this repo. Under the root directory, we have subdirectories with `index.js` (after transpilation), and these subpaths are exported in package.json as such:

```json
".": {
  "import": {
    "types": "./build/esm/index.d.ts",
    "default": "./build/esm/index.js"
  },
  "require": {
    "types": "./build/cjs/index.d.ts",
    "default": "./build/cjs/index.js"
  }
},
"./*": {
  "import": {
    "types": "./build/esm/*/index.d.ts",
    "default": "./build/esm/*/index.js"
  },
  "require": {
    "types": "./build/cjs/*/index.d.ts",
    "default": "./build/cjs/*/index.js"
  }
}
```

I couldn't find a way to configure `typesVersions` in a way that would make TS happy with both the root and subpath exports. `"*": { "*": ["build/cjs/*"] }` makes the subpaths unresolved, while `"*": { ".": ["build/cjs/index.d.ts"], "*": ["build/cjs/*/index.d.ts"] }` has problems with the root export.

I created a minimal repro in https://github.com/michaldudak/attw-repro and I'd appreciate any help (and mentioning such a case in the ATTW docs).

**Comment by andrewbranch** [comment]
`typesVersions` doesn’t recognize `"."` as a special entry, since it doesn’t require leading `./` on subpaths like `exports`. Instead, when resolving `"attw-repro"`, the `types` field is applied first to make the lookup `./node_modules/attw-repro/index.d.ts`, and then `index.d.ts` is piped into the `typesVersions` map. So, one valid solution looks like this:

```
  "types": "index",
  "typesVersions": {
    "*": {
      "index": [
        "build/cjs/index.d.ts"
      ],
      "*": [
        "build/cjs/*/index.d.ts"
      ]
    }
  },
```
