### ISSUE TITLE
Question: Why define both main and exports in package.json of types-versions-wildcards

### ISSUE THREAD

**Issue by mrrajamanickam-coveo** [andrewbranch/example-subpath-exports-ts-compat#9]
https://github.com/andrewbranch/example-subpath-exports-ts-compat/blob/main/examples/node_modules/types-versions-wildcards/package.json has both `main` and `exports` defined. But the solution works only for Node >= 12. Wouldn't it make sense to remove `main` then to keep it simpler and avoid any confusion?

**Comment by andrewbranch** [comment]
The purpose of the examples in this repo was to show ways of making TypeScript not complain even when users are using an old version of it or the wrong settings. TypeScript won’t look at `exports` unless `moduleResolution` is set to `node16`, `nodenext`, or `bundler`. When it’s set to something else, `main` will be necessary for TS to work. Users _should_ be using one of those settings unless they’re actually using Node <= 11, but many still aren’t, so libraries that want to provide really high levels of TS compatibility sometimes want to trick old TypeScript / old settings into behaving like new TypeScript / new settings.
